appId: "77A8C8C7-82A1-4321-AB12-DF7890123456"
appName: "IoTDevKit"
displayName: "IoT DevKit"
publisher: "Chen Yannan"
publisherUrl: "https://github.com/bcblr1993/iot_devkit_flutter"
startMenu:
  folder: "IoT DevKit"
